---

- name: restart flanneld
  service: 
    name=flanneld 
    state=restarted

- name: enable flanneld
  service: 
    name=flanneld 
    enabled=yes

- name: restart docker
  service: 
    name=docker 
    state=restarted

