---

- name: Disable swap
  include: swapoff.yml
  tags: configure

# Install the kube node components
# E.g. applying package manager, downloading binaries from github, etc.
- name: Install kube node
  include: install.yml
  tags: install

# Configure and start node components
# I.e. kubelet and proxy
- name: Collect tokens for kubelet and proxy
  include: collect-tokens.yml
  tags: configure

- name: Configure kubelet
  include: kubelet-configure.yml
  tags: configure

- name: Start kubelet
  include: kubelet-start.yml

- name: Configure proxy
  include: proxy-configure.yml
  tags: configure

- name: Start proxy
  include: proxy-start.yml

# Networking
- include: firewalld.yml
  when: has_firewalld
  tags: configure

# Restart services - this happens when a cluster has a service already running
# Either from previous ansible deployment or on an already set up cluster
- name: Call restart kubelet
  include: kubelet-restart.yml
  when: kubelet_modified == true and kubelet_started.changed == false
  tags: restart

- name: Call restart proxy
  include: proxy-restart.yml
  when: proxy_modified == true and proxy_started.changed == false
  tags: restart

