---

flanneld_started: true
flanneld_enable: true

# default configuration directory
flannel_config_dir: "/etc/sysconfig"

flannel_url_scheme: "{{ etcd_url_scheme | default('http') }}"

flannel_client_port: "{{ etcd_client_port | default(2379) }}"

flannel_cluster_name: "{{ etcd_cluster_name | default('kube-centos') }}"

etcd_client_port: 2379

#flannel_version
flannel_version: 0.5.5

#The backend that flannel should use
flannel_backend: vxlan

#The default url to download the flannel tar from
flannel_download_url_base: "https://github.com/coreos/flannel/releases/download/v{{ flannel_version }}"
flannel_download_url: "{{ flannel_download_url_base }}/flannel-{{ flannel_version }}-linux-amd64.tar.gz"

flannel_etcd_use_certs: false
flannel_etcd_certs_dir: "/etc/flanneld/certs"
flannel_etcd_ca_file: "{{ flannel_etcd_certs_dir }}/ca.crt"
flannel_etcd_cert_file: "{{ flannel_etcd_certs_dir }}/client.crt"
flannel_etcd_key_file: "{{ flannel_etcd_certs_dir }}/client.key"

