---

- name: Create etcd config directory
  file: 
    path={{ etcd_conf_dir }} 
    state=directory

- name: Write etcd config file
  template: 
    src=etcd.conf.j2 
    dest=/etc/etcd/etcd.conf

- name: Setting the etcd_modified fact to true
  set_fact:
    etcd_modified: true

- name: Configure firewalld
  include: firewalld-configure.yml

