---

- name: Install etcd package
  package:
    name=etcd
    state=latest

- name: Copy certificates if specified
  include: gen-certs.yml
  when: etcd_url_scheme == 'https' or etcd_peer_url_scheme == 'https'

