---

- name: Install etcd package
  include: install.yml
  tags: install

- name: Configure etcd package
  include: configure.yml
  tags: configure

# etcd.service needs to be running to configure etcd-network or to 
# start flanneld.service
- name: Start etcd package
  include: start-etcd.yml

