---
# On stock Core OS there is no /etc/hosts.
- name: Check is /etc/hosts file exists
  stat: 
    path=/etc/hosts
  register: hosts

- name: Create hosts file if it is not present
  file: 
    path=/etc/hosts 
    state=touch
  when: not hosts.stat.exists

- name: Write etcd config file
  template: 
    src=etc_hosts.j2 
    dest=/etc/hosts

